fixup (2)

diff --git a/.github/workflows/fmudataio-documention.yml b/.github/workflows/fmudataio-documention.yml
--- a/.github/workflows/fmudataio-documention.yml
+++ b/.github/workflows/fmudataio-documention.yml
@@ -1,11 +1,9 @@
 # build and test some end points
 name: Build and deploy docs for fmu-dataio
 
-# on: [push, pull_request]
-
 on:
-  # pull_request:
-  #   branches: [main]
+  pull_request:
+    branches: [main]
   push:
     branches: [main]
 
@@ -34,41 +32,19 @@ jobs:
           pip install git+https://github.com/equinor/fmu-config
           sh examples/run_examples.sh
           python setup.py build_sphinx
-      - name: Update GitHub pages
-        if: github.repository_owner == 'equinor' && github.ref == 'refs/heads/main'
-        run: |
-          cp -R ./build/sphinx/html ../html
-          git config --local user.email "fmu-dataio-github-action"
-          git config --local user.name "fmu-dataio-github-action"
-          git fetch origin gh-pages
-          git checkout --track origin/gh-pages
-          git clean -f -f -d -x  # Double -f is intentional.
-          git rm -r *
-          cp -R ../html/* .
-          touch .nojekyll  # If not, github pages ignores _* directories.
-          git add .
-          echo "Ready for commit"
-          if git diff-index --quiet HEAD; then
-            echo "No changes in documentation. Skip documentation deploy."
-          else
-            git commit -m "Update Github Pages"
-            git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" gh-pages
-          fi
       - name: Commit documentation changes
         run: |
-          git fetch origin gh-pages
-          git checkout --track origin/gh-pages
           mkdir -p gh-pages
           cp -R build/sphinx/html/* gh-pages/
-          cd gh-pages
-          git config --local user.email "action@github.com"
-          git config --local user.name "GitHub Action"
-          git add .
-          git commit -m "Update documentation" -a || true
-          # The above command fails if no changes, so we ignore the return code.
+          # cd gh-pages
+          # git add .
+          # git commit -m "Update documentation" -a || true
+          # # The above command fails if no changes, so we ignore the return code.
       - name: Push changes
-        uses: ad-m/github-push-action@master
+        uses: peaceiris/actions-gh-pages@v3
         with:
-          branch: gh-pages
-          directory: gh-pages
-          github_token: ${{ secrets.GITHUB_TOKEN }}
+          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
+          publish_dir: ./gh_pages
+          allow_empty_commit: true
+          user_name: "github-actions[bot]"
+          user_email: "github-actions[bot]@users.noreply.github.com"
